reorganize files, placeholder for human-visualizer

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -17,7 +17,7 @@ jobs:
       - name: Build Images
         run: docker compose build --parallel
 
-  pytest:
+  pytest-game-engine:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout
@@ -28,7 +28,11 @@ jobs:
 
       - name: Build and Run Tests
         working-directory: ${{ github.workspace }}
-        run: docker compose -f docker-compose-dev-zscaler-integrationtest.yml up --build -d
+        run: docker compose -f docker-compose-dev-zscaler.yml -f docker-compose-tests.yml up --build -d \
+          mqtt-broker \
+          game-engine \
+          game-engine-integration-test \
+          gameboard
 
       - name: Wait for integration-test container to exit
         run: timeout 600 docker wait integration-test
@@ -56,4 +60,45 @@ jobs:
           name: test-artifacts
           path: results.xml
 
-     
+  pytest-human-visualizer:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v4
+
+      - name: Set up Docker Buildx
+        uses: docker/setup-buildx-action@v3
+
+      - name: Build and Run Tests
+        working-directory: ${{ github.workspace }}
+        run: docker compose -f docker-compose-dev-zscaler.yml -f docker-compose-tests.yml up --build -d \
+          mqtt-broker \
+          game-engine \
+          human-visualizer-integration \
+          gameboard
+
+      - name: Wait for integration-test container to exit
+        run: timeout 600 docker wait integration-test
+
+      - name: Stop Container
+        if: always()
+        run: docker compose down
+
+      - name: Check Logs
+        run: docker logs integration-test
+
+      - name: Copy Test Results
+        run: docker cp integration-test:/app/results.xml ${{ github.workspace }}/results.xml
+          
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: ${{ github.workspace }}/results.xml
+
+      - name: Upload Test Results
+        if: always()
+        uses: actions/upload-artifact@v4
+        with:
+          name: test-artifacts
+          path: results.xml
