publish test report and take down containers

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -40,7 +40,14 @@ jobs:
         run: docker cp integration-test:/app/results.xml ${{ github.workspace }}/results.xml
 
       - name: Stop Container
-        run: docker-compose down
+        if: always()
+        run: docker compose down
+          
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: ${{ github.workspace }}/results.xml
 
       - name: Upload Test Results
         if: always()
@@ -48,4 +55,5 @@ jobs:
         with:
           name: test-artifacts
           path: results.xml
+
      
